server:
  port: 9000
spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://auth-server:9000
        client:
          messages-client:
            registration:
              client-id: messages-client
              client-secret: "{noop}secret"
              client-name: Messages Client
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
                - client_credentials
              redirect-uris:
                - http://localhost:8080/login/oauth2/code/messages-client-oidc
                - http://localhost:8080/authorized
              scopes:
                - openid
                - messages.read
logging:
  level:
    org: INFO
