server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          messages-client-oidc:
            provider: spring
            client-id: messages-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: messages-client-oidc
          messages-client-authorization-code:
            provider: spring
            client-id: messages-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/authorized"
            scope: messages.read
            client-name: messages-client-authorization-code
        provider:
          spring:
            issuer-uri: http://auth-server:9000

logging:
  level:
    org: TRACE